"""Database module for SQLite connection, schema management, and seeding."""

from database.database import (
    DEFAULT_DB_PATH,
    PROJECT_ROOT,
    execute_query,
    get_connection,
    get_db_path,
    get_engine,
    get_foreign_keys,
    get_sample_data,
    get_schema_ddl,
    get_schema_prompt_context,
    get_table_counts,
    get_table_info,
    get_table_names,
    init_db,
    resolve_db_uri,
    validate_database_connection,
    validate_connection,
    test_connection,
    test_database_connection,
)

__all__ = [
    "DEFAULT_DB_PATH",
    "PROJECT_ROOT",
    "execute_query",
    "get_connection",
    "get_db_path",
    "get_engine",
    "get_foreign_keys",
    "get_sample_data",
    "get_schema_ddl",
    "get_schema_prompt_context",
    "get_table_counts",
    "get_table_info",
    "get_table_names",
    "init_db",
    "resolve_db_uri",
    "validate_database_connection",
    "validate_connection",
    "test_connection",
    "test_database_connection",
]
